### ISSUE TITLE
React Feather feedback

### ISSUE THREAD

**Issue by The-Code-Monkey** [DominiqueGarmier/slurpli#1]
Hey there i noticed you added my version of react feather and was just wondering about a few things.

How are you finding it?
Would you benefit from an Icon component that can be used like so.
```
<Icon name="Github" />
```

**Comment by DominiqueGarmier** [comment]
I have never really encountered that use case, so for me personally no. but I could definitely see this being useful, if for example an icon could be selected by a user. So i'd say it's definitely a useful feature non the less. 👍

**Comment by The-Code-Monkey** [comment]
Thanks for the feedback I'll leave you alone now. If you need any icons adding please raise an issue
